services:
  app:
    build: .
    ports:
      - "8765:80"
    volumes:
      - traces:/app/var/traces
      - ${TRACES_DIR}:/traces:ro
      - ${SOURCE_HOST_DIR}:${SOURCE_CONTAINER_DIR}:ro
      - ./symfony/src:/app/src
      - ./symfony/migrations:/app/migrations
      - ./symfony/public/app:/app/public/app
      - ./docker-compose.yml:/compose/compose.yaml:rw
    depends_on:
      - db
    environment:
      APP_ENV: dev
      APP_SECRET: change_me_in_production
      DATABASE_URL: postgresql://xtrace:xtrace@db:5432/xtrace?serverVersion=16&charset=utf8
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
      CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$$'
      DEFAULT_URI: http://localhost:8765
      TRACES_SOURCE_DIR: /traces
      COMPOSE_FILE_PATH: /compose/compose.yaml

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: xtrace
      POSTGRES_USER: xtrace
      POSTGRES_PASSWORD: xtrace
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  traces:
  pgdata:
