<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260621000002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create favourite_pattern table (entity existed but no migration)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE favourite_pattern (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            pattern VARCHAR(500) NOT NULL,
            label VARCHAR(200) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE favourite_pattern');
    }
}
